version: '3.9'

services:
  java-service:
    build:
      context: ../
      dockerfile: docker-service/Dockerfile
    image: backend-java-app:latest
    container_name: java-service
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/keuangan?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=adminkeuangan
      - SPRING_DATASOURCE_PASSWORD=Gedell123!@#
    volumes:
      - ./logs:/app/logs
    restart: always
    networks:
      - mysql-service_my_network

networks:
  mysql-service_my_network:
    external: true
