pipeline {
    agent any

    environment {
        // Menggunakan nama tool yang telah dikonfigurasi di Jenkins
        MVN_HOME = tool name: 'maven', type: 'maven'
        JAVA_HOME = tool name: 'JDK-11', type: 'jdk'
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone the code from GitHub
                checkout([$class: 'GitSCM',
                    branches: [[name: 'main']],
                    userRemoteConfigs: [[url: 'https://github.com/fadelrahmatullah/java-finance.git']]
                ])
            }
        }

        stage('Build') {
            steps {
                // Build the application using Maven
                sh "${MVN_HOME}/bin/mvn clean package"
            }
        }

        stage('Test') {
            steps {
                // Run unit tests (optional)
                sh "${MVN_HOME}/bin/mvn test"
            }
        }

        stage('Deploy') {
            steps {
                // Deploy the application (define your deployment steps here)
                echo 'Deployment process goes here'
                // Example: copy the JAR file to a deployment directory or server
                // sh 'scp target/*.jar user@server:/path/to/deploy'
            }
        }
    }

    post {
        always {
            // Clean up workspace or any additional tasks
            cleanWs()
        }
    }
}
