pipeline {
    agent any

    environment {
        MVN_HOME = tool name: 'maven', type: 'maven'
        JAVA_HOME = tool name: 'JDK-11', type: 'jdk'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: 'main']],
                    userRemoteConfigs: [[url: 'https://github.com/fadelrahmatullah/java-finance.git']]
                ])
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application'
                sh "${MVN_HOME}/bin/mvn clean package"
            }
        }

        stage('Test') {
            steps {
                echo 'Running unit tests'
                sh "${MVN_HOME}/bin/mvn test"
            }
        }

        stage('Run Application') {
            steps {
                echo 'Running the application'
                // Pastikan Anda telah membangun aplikasi dan file JAR ada di direktori target
                sh 'java -jar target/your-app.jar'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deployment process goes here'
                // Deployment commands for the application
            }
        }
    }

    post {
        success {
            echo 'Build and deployment were successful'
        }
        failure {
            echo 'Build or deployment failed'
        }
        always {
            cleanWs()
        }
    }
}
